# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Projeye özgü ek linter kuralları buraya gelebilir:
    # avoid_print: true
    # prefer_const_constructors: true
